[env:reterminal_e1002]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-10
upload_speed = 230400
board_build.extra_flags =
  -D ARDUINO_XIAO_ESP32S3
  -D BOARD_HAS_PSRAM
build_flags =
  -D ARDUINO_USB_MODE=0
  -D ARDUINO_USB_CDC_ON_BOOT=0
lib_deps =
  https://github.com/Seeed-Projects/Seeed_GxEPD2.git#master
  bblanchon/ArduinoJson @ ^7.4.2
  tzapu/WiFiManager @ ^2.0.17
